import { SubtitleStyle, SubtitlePreset } from "./types";

export const DEFAULT_SUBTITLE_STYLE: SubtitleStyle = {
  enabled: true,
  preset: "plain",
  fontFamily: "Inter",
  fontSize: 44,
  primaryColor: "#FFFFFF",
  secondaryColor: "#FFFFFF",
  highlightColor: "#FFFFFF",
  outlineColor: "#000000",
  outlineWidth: 2.0,
  boxColor: "#000000",
  boxOpacity: 0.0,
  karaokeEnabled: false,
  allCaps: false,
  textCase: "uppercase",
  autoEmoji: false,
  positionX: 50,
  positionY: 80,
  rotation: 0,
  boxWidthMode: "custom",
  boxWidth: 76,
  scaleX: 1,
  scaleY: 1,
};

export const PRESET_STYLES: Record<string, Partial<SubtitleStyle>> = {
  plain: {
    fontFamily: "Inter",
    fontSize: 44,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 2.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: false,
    allCaps: false,
    textCase: "uppercase",
    autoEmoji: false,
    positionY: 80,
    enabled: true,
  },
  hormozi: {
    fontFamily: "Anton",
    fontSize: 48,
    primaryColor: "#FFFFFF",
    secondaryColor: "#FACC15",
    highlightColor: "#FACC15",
    outlineColor: "#000000",
    outlineWidth: 3.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  beast: {
    fontFamily: "Bebas Neue",
    fontSize: 48,
    primaryColor: "#FFFFFF",
    secondaryColor: "#38BDF8",
    highlightColor: "#38BDF8",
    outlineColor: "#000000",
    outlineWidth: 3.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  clean_box: {
    fontFamily: "Inter",
    fontSize: 38,
    primaryColor: "#FFFFFF",
    secondaryColor: "#38BDF8",
    highlightColor: "#38BDF8",
    outlineColor: "#000000",
    outlineWidth: 0,
    boxColor: "#000000",
    boxOpacity: 0.8,
    karaokeEnabled: true,
    allCaps: false,
    enabled: true,
  },
  neon: {
    fontFamily: "Syne",
    fontSize: 42,
    primaryColor: "#F472B6",
    secondaryColor: "#A855F7",
    highlightColor: "#A855F7",
    outlineColor: "#581C87",
    outlineWidth: 3.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  minimal: {
    fontFamily: "Inter",
    fontSize: 36,
    primaryColor: "#F4F4F5",
    secondaryColor: "#E4E4E7",
    highlightColor: "#FFFFFF",
    outlineColor: "#18181B",
    outlineWidth: 2.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: false,
    allCaps: false,
    enabled: true,
  },
  devin: {
    fontFamily: "Fira Code",
    fontSize: 38,
    primaryColor: "#22D3EE",
    secondaryColor: "#F43F5E",
    highlightColor: "#F43F5E",
    outlineColor: "#082F49",
    outlineWidth: 2.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: false,
    enabled: true,
  },
  bold_yellow: {
    fontFamily: "Impact",
    fontSize: 48,
    primaryColor: "#FACC15",
    secondaryColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 3.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  retro_glow: {
    fontFamily: "Syne",
    fontSize: 42,
    primaryColor: "#F59E0B",
    secondaryColor: "#EF4444",
    highlightColor: "#EF4444",
    outlineColor: "#78350F",
    outlineWidth: 3.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  cinematic: {
    fontFamily: "Playfair Display",
    fontSize: 36,
    primaryColor: "#E2E8F0",
    secondaryColor: "#94A3B8",
    highlightColor: "#F8FAFC",
    outlineColor: "#0F172A",
    outlineWidth: 2.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: false,
    allCaps: false,
    enabled: true,
  },
  cyberpunk: {
    fontFamily: "Syne",
    fontSize: 44,
    primaryColor: "#00F0FF",
    secondaryColor: "#FFE600",
    highlightColor: "#FFE600",
    outlineColor: "#000000",
    outlineWidth: 3.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  midnight: {
    fontFamily: "Outfit",
    fontSize: 40,
    primaryColor: "#60A5FA",
    secondaryColor: "#3B82F6",
    highlightColor: "#93C5FD",
    outlineColor: "#1E3A8A",
    outlineWidth: 2.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: false,
    enabled: true,
  },
  fire_red: {
    fontFamily: "Anton",
    fontSize: 46,
    primaryColor: "#EF4444",
    secondaryColor: "#F97316",
    highlightColor: "#FEF08A",
    outlineColor: "#450A0A",
    outlineWidth: 3.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  emerald_glow: {
    fontFamily: "Outfit",
    fontSize: 40,
    primaryColor: "#10B981",
    secondaryColor: "#34D399",
    highlightColor: "#A7F3D0",
    outlineColor: "#064E3B",
    outlineWidth: 2.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: false,
    enabled: true,
  },
  comic_pop: {
    fontFamily: "Bungee",
    fontSize: 42,
    primaryColor: "#FBBF24",
    secondaryColor: "#EC4899",
    highlightColor: "#FFFFFF",
    outlineColor: "#18181B",
    outlineWidth: 4.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  nordic_minimal: {
    fontFamily: "Inter",
    fontSize: 34,
    primaryColor: "#E4E4E7",
    secondaryColor: "#A1A1AA",
    highlightColor: "#FFFFFF",
    outlineColor: "#27272A",
    outlineWidth: 1.5,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: false,
    allCaps: false,
    enabled: true,
  },
  synthwave: {
    fontFamily: "Syne",
    fontSize: 42,
    primaryColor: "#EC4899",
    secondaryColor: "#8B5CF6",
    highlightColor: "#06B6D4",
    outlineColor: "#312E81",
    outlineWidth: 3.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: true,
    enabled: true,
  },
  ali: {
    fontFamily: "Merriweather",
    fontSize: 34,
    primaryColor: "#FEF08A",
    secondaryColor: "#FFFFFF",
    highlightColor: "#FEF08A",
    outlineColor: "#451A03",
    outlineWidth: 2.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: false,
    allCaps: false,
    enabled: true,
  },
  custom: {
    fontFamily: "Inter",
    fontSize: 40,
    primaryColor: "#FFFFFF",
    secondaryColor: "#3B82F6",
    highlightColor: "#3B82F6",
    outlineColor: "#000000",
    outlineWidth: 3.0,
    boxColor: "#000000",
    boxOpacity: 0.0,
    karaokeEnabled: true,
    allCaps: false,
    enabled: true,
  },
};

export const SUBTITLE_PRESET_OPTIONS: Array<{
  id: SubtitlePreset;
  name: string;
  badge: string;
  description: string;
}> = [
  { id: "plain", name: "Standard Clean", badge: "White Minimal", description: "Crisp white subtitles with dark stroke" },
  { id: "hormozi", name: "Hormozi Viral", badge: "Yellow Pop", description: "Bold yellow active glow, high retention" },
  { id: "beast", name: "MrBeast Action", badge: "Sky Blue", description: "Punchy sky blue & white stroke" },
  { id: "clean_box", name: "Clean Modern Box", badge: "Dark Box", description: "Modern semi-transparent box background" },
  { id: "neon", name: "Neon Cyberpunk", badge: "Pink/Purple", description: "Electric pink and purple neon aura" },
  { id: "minimal", name: "Nordic Minimal", badge: "Soft Clean", description: "Subtle and elegant minimalist typography" },
  { id: "devin", name: "Devin Code", badge: "Cyan Mono", description: "Fira Code cyan developer style" },
  { id: "bold_yellow", name: "Bold Yellow", badge: "High Contrast", description: "High contrast yellow impact" },
  { id: "retro_glow", name: "80s Retro Glow", badge: "Amber Glow", description: "Warm amber & red retro glow" },
  { id: "cinematic", name: "Cinematic Movie", badge: "Serif Elegance", description: "Editorial Playfair serif elegance" },
  { id: "cyberpunk", name: "Cyberpunk 2077", badge: "Neon Cyan", description: "Neon cyan & laser yellow" },
  { id: "midnight", name: "Midnight Glow", badge: "Deep Blue", description: "Deep blue electric highlight" },
  { id: "fire_red", name: "Fire Red Energy", badge: "Red Impact", description: "Intense energetic red glow" },
  { id: "emerald_glow", name: "Emerald Glow", badge: "Emerald", description: "Vibrant emerald green highlights" },
  { id: "comic_pop", name: "Comic Pop", badge: "Pop Bubble", description: "Punchy comic book display font" },
  { id: "nordic_minimal", name: "Nordic Minimal Light", badge: "Ultra Clean", description: "Ultra-clean Scandinavian style" },
  { id: "synthwave", name: "Synthwave", badge: "Retrowave", description: "80s retrowave magenta & cyan" },
];

export function getPresetSubtitleStyle(preset?: SubtitlePreset | string): SubtitleStyle {
  const p = (preset || "plain") as SubtitlePreset;
  const overrides = PRESET_STYLES[p] || PRESET_STYLES.plain;
  return {
    ...DEFAULT_SUBTITLE_STYLE,
    ...overrides,
    preset: p,
    enabled: true,
  };
}
